- README.md
- src/base_cache_filesystem.cpp
- src/disk_cache_filesystem.cpp
- src/in_memory_cache_filesystem.cpp
- src/include/base_cache_filesystem.hpp
- src/include/cache_filesystem_config.hpp
- src/include/disk_cache_filesystem.hpp
- src/include/in_mem_cache_block.hpp
duckdb uses `idx_t` to represent unsigned integers (i.e. offset, file size, indexes, etc).
Also update documentation to reflect local cache file eviction policy.
> Use duckdb native type and functions

- CMakeLists.txt
- src/disk_cache_filesystem.cpp
- src/utils/include/thread_utils.hpp
- src/utils/thread_utils.cpp
`pthread_setname_np` has different declaration on macos and linux platform.
> Fix pthread issue on macos

- CMakeLists.txt
- src/base_cache_filesystem.cpp
- src/disk_cache_filesystem.cpp
- src/in_memory_cache_filesystem.cpp
- src/include/base_cache_filesystem.hpp
- src/include/disk_cache_filesystem.hpp
- src/include/in_memory_cache_filesystem.hpp
- unit/test_base_cache_filesystem.cpp
- Allow cache filesystem to wrap around local filesystem, previously it doesn't work because local filesystem `CanHandle` returns false at all times;
- Update `GetName` implementation for cached filesystem instances to include internal filesystem name.
> Fix cache filesystem for local filesystem inside

- src/disk_cache_filesystem.cpp
- src/in_memory_cache_filesystem.cpp
- src/include/cache_filesystem_config.hpp
- src/include/in_memory_cache_filesystem.hpp
- src/read_cache_fs_extension.cpp
- unit/test_set_extension_config.cpp
- Add more configurations to cache filesystem, including cache block size and in-memory max block count;
- Add more unit test for config settings.
> Add other configs for cache filesystem

- .clang-format
- benchmark/read_s3_object.cpp
- src/base_cache_filesystem.cpp
- src/disk_cache_filesystem.cpp
- src/in_memory_cache_filesystem.cpp
- src/include/base_cache_filesystem.hpp
- src/include/cache_filesystem_config.hpp
- src/include/disk_cache_filesystem.hpp
- src/include/in_mem_cache_block.hpp
- src/include/in_memory_cache_filesystem.hpp
- src/include/read_cache_fs_extension.hpp
- src/read_cache_fs_extension.cpp
- src/utils/filesystem_utils.cpp
- src/utils/include/filesystem_utils.hpp
- src/utils/include/lru_cache.hpp
- src/utils/include/map_utils.hpp
- src/utils/include/resize_uninitialized.hpp
- src/utils/include/size_literals.hpp
- src/utils/include/type_traits.hpp
- src/utils/thread_utils.cpp
- unit/test_base_cache_filesystem.cpp
- unit/test_disk_cache_filesystem.cpp
- unit/test_in_memory_cache_filesystem.cpp
- unit/test_set_extension_config.cpp
- unit/test_shared_lru_cache.cpp
- unit/test_size_literals.cpp
- unit/test_stale_deletion.cpp
This PR updates clang-format configuration file to use duckdb's.
Ref: https://github.com/duckdb/duckdb/blob/main/.clang-format
> Update clang-format to use duckdb's

- src/base_cache_filesystem.cpp
- src/cache_filesystem_config.cpp
- src/in_memory_cache_filesystem.cpp
- src/include/in_mem_cache_block.hpp
- src/include/in_memory_cache_filesystem.hpp
Cache reader could be accessed from multiple threads, so need to make sure it's thread-safety.
> Fix data race for in-memory cache reader

- unit/test_disk_cache_filesystem.cpp
- unit/test_in_memory_cache_filesystem.cpp
Resolves https://github.com/dentiny/duck-read-cache-fs/issues/35, to add more testcases to cover concurrent accesses.
> Add testcases for concurrent access for both cache filesystem

- CMakeLists.txt
- src/base_cache_filesystem.cpp
- src/cache_filesystem_config.cpp
- src/disk_cache_filesystem.cpp
- src/in_memory_cache_filesystem.cpp
- src/include/base_cache_filesystem.hpp
- src/include/base_cache_reader.hpp
- src/include/base_profile_collector.hpp
- src/include/cache_filesystem_config.hpp
- src/include/in_mem_cache_block.hpp
- src/include/temp_profile_collector.hpp
- src/read_cache_fs_extension.cpp
- src/temp_profile_collector.cpp
- src/utils/include/time_utils.hpp
- unit/test_disk_cache_filesystem.cpp
- unit/test_in_memory_cache_filesystem.cpp
Example usage:
```
D LOAD read_cache_fs;
D SELECT cache_httpfs_get_latest_profile();
┌─────────────────────────────────────┐
│  cache_httpfs_get_latest_profile()  │
│               varchar               │
├─────────────────────────────────────┤
│ No valid access to cache filesystem │
└─────────────────────────────────────┘
D SET cached_http_profile_type='temp';
D select * from read_csv_auto('https://csvbase.com/meripaterson/stock-exchanges');
<content>
D SELECT cache_httpfs_get_latest_profile();
┌───────────────────────────────────┐
│ cache_httpfs_get_latest_profile() │
│              varchar              │
├───────────────────────────────────┤
│ (noop profile collector)          │
└───────────────────────────────────┘
D COPY (SELECT cache_httpfs_get_profile()) TO '/tmp/output.txt';
-- …
```
> Initial implementation for cache filesystem profiler

- CMakeLists.txt
- benchmark/read_s3_object.cpp
- src/cache_filesystem.cpp
- src/disk_cache_reader.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_cache_reader.hpp
- src/include/cache_filesystem.hpp
- src/include/disk_cache_reader.hpp
- src/include/in_memory_cache_reader.hpp
- src/include/noop_cache_reader.hpp
- src/noop_cache_reader.cpp
- src/read_cache_fs_extension.cpp
- unit/test_base_cache_filesystem.cpp
- unit/test_disk_cache_filesystem.cpp
- unit/test_in_memory_cache_filesystem.cpp
- unit/test_noop_cache_reader.cpp
- unit/test_set_extension_config.cpp
- Expose duckdb functions to clear cache for all cache readers;
- Rename cache filesystem into cache readers.
> Clear cache for all cached reader

- README.md
- src/include/read_cache_fs_extension.hpp
- src/read_cache_fs_extension.cpp
As titled, this PR loads httpfs internally before we load cached version, which include all necessary type/function/... to access remote resource, so users only need to load one single extension.
> Load httpfs extension inside of cache extension

- CMakeLists.txt
- src/read_cache_fs_extension.cpp
- src/utils/histogram.cpp
- src/utils/include/histogram.hpp
- unit/test_histogram.cpp
Later on, I will integrate it with `cache_httpfs_get_profile` function to provide more cache access information.
> Add a util of historgram to display purpose

- CMakeLists.txt
- src/histogram.cpp
- src/include/histogram.hpp
- src/include/temp_profile_collector.hpp
- src/temp_profile_collector.cpp
- unit/test_histogram.cpp
Example SQL:
```
COPY (SELECT cache_httpfs_get_profile()) TO '/tmp/output.txt';
```
Example result:
```
For temp profile collector and stats for on_disk_cache_reader (unit in milliseconds)
cache hit count = 2
cache miss count = 1
IO latency is Max = 88.000000
Min = 88.000000
Mean = 88.000000
```
> Integrate histogram into profiler

- src/cache_filesystem.cpp
- src/disk_cache_reader.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_profile_collector.hpp
- src/include/temp_profile_collector.hpp
- src/temp_profile_collector.cpp
This PR adds a new cache access category for metadata access.
Example output:
```
For temp profile collector and stats for in_mem_cache_reader (unit in milliseconds)
metadata cache hit count = 15
metadata cache miss count = 1
data block cache hit count = 5
data block cache miss count = 1
IO latency is Max = 89.000000
Min = 89.000000
Mean = 89.000000
```
> Record file metadata cache access

- src/cache_filesystem.cpp
- src/disk_cache_reader.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_cache_reader.hpp
- src/include/cache_filesystem.hpp
- src/include/disk_cache_reader.hpp
- src/include/in_memory_cache_reader.hpp
- src/include/noop_cache_reader.hpp
- src/read_cache_fs_extension.cpp
- src/utils/include/lru_cache.hpp
- unit/test_shared_lru_cache.cpp
As titled, we're now able to clear in-memory cache entry and on-disk files for the given filename.
> Clear cache entries for the single file

- benchmark/read_s3_object.cpp
See inline reference for details. In addition, signals should be handled in main program rather than library.
> Ignore SIGPIPE in benchmark

- src/histogram.cpp
- src/include/histogram.hpp
- src/temp_profile_collector.cpp
Example output:
```
For temp profile collector and stats for in_mem_cache_reader (unit in milliseconds)
metadata cache hit count = 15
metadata cache miss count = 1
data block cache hit count = 5
data block cache miss count = 1
IO latency is Max = 92.000000
Min = 92.000000
Mean = 92.000000
Distribution latency [90.000000, 95.000000) millisec: 100.000000 %
```
> Add distributuion format string for histogram

- src/disk_cache_reader.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_profile_collector.hpp
- src/include/temp_profile_collector.hpp
- src/temp_profile_collector.cpp
It's possible that a filesystem goes through requests with the same starting offset, so should use a unique ID to differentiate.
> Fix duplicate operation id

- src/cache_filesystem.cpp
SetAndGetCacheReader missed a return in Noop case
> Add missing return

- CMakeLists.txt
- benchmark/rand_utils.hpp
- benchmark/random_read_benchmark.cpp
Hardward config:
```
ubuntu@hjiang-devbox-pg$ lscpu
Architecture:            x86_64
CPU op-mode(s):        32-bit, 64-bit
Address sizes:         46 bits physical, 48 bits virtual
Byte Order:            Little Endian
CPU(s):                  32
On-line CPU(s) list:   0-31
Caches (sum of all):     
L1d:                   512 KiB (16 instances)
L1i:                   512 KiB (16 instances)
L2:                    16 MiB (16 instances)
L3:                    35.8 MiB (1 instance)
ubuntu@hjiang-devbox-pg$ lsmem 
RANGE                                   SIZE  STATE REMOVABLE   BLOCK
0x0000000000000000-0x00000000bfffffff     3G online       yes    0-23
0x0000000100000000-0x0000001fe7ffffff 123.6G online       yes 32-1020
Memory block size:       128M
Total online memory:    126.6G
Total offline …
```
> Add random access benchmark

- src/read_cache_fs_extension.cpp
- unit/test_disk_cache_filesystem.cpp
Cache directory is only created on directory changes, so default directory should be created on extension load.
> Create default disk cache directory

- src/cache_filesystem.cpp
- src/cache_filesystem_config.cpp
- src/include/cache_filesystem.hpp
- src/include/cache_filesystem_config.hpp
- src/read_cache_fs_extension.cpp
Metadata could be already cached in the underlying filesystem, depending on the implementation; this PR provides an option to disable on cache fs level.
> Provide an options to disable metadata cache

- README.md
- benchmark-graph/random-performance-barchart.svg
- benchmark-graph/seq-performance-barchart.svg
- benchmark/README.md
- benchmark/random_read_benchmark.cpp
- benchmark/sequential_read_benchmark.cpp
- src/utils/thread_utils.cpp
Add performance benchmark documentation comparing DuckDB native httpfs vs Cache FS Extension for sequential S3 reads.
> Add benchmark README

- README.md
- benchmark/random_read_benchmark.cpp
- benchmark/read_s3_object.cpp
- benchmark/sequential_read_benchmark.cpp
- src/cache_filesystem_config.cpp
- src/include/cache_filesystem_config.hpp
- src/read_cache_fs_extension.cpp
- unit/test_disk_cache_filesystem.cpp
- unit/test_filesystem_config.cpp
- unit/test_set_extension_config.cpp
- unit/test_stale_deletion.cpp
- Rename extension config settings and functions to uniformly prefixed with `cache_httpfs_`
- Add a new option to ignore SIGPIPE, see inline comments for reference
> Provide option to ignore SIGPIPE

- CMakeLists.txt
- README.md
- Update extension dependencies: (1) update duckdb to v1.2.0; (2) extension tools and httpfs to latest main commit
- Skip build duckdb non-core targets, for example, tests, docs, etc
> Disable duckdb non-core codebase

- src/noop_cache_reader.cpp
- src/read_cache_fs_extension.cpp
- unit/test_noop_cache_reader.cpp
This PR does three things:
- When we delete all cache files under on-disk cache directory, we should recreate after deletion;
- Use UUID for operation id from profiler, otherwise we could suffer profiling key collision;
- Add a unit test for noop cache reader.
> Fix on noop reader profile

- src/cache_filesystem.cpp
- src/in_memory_cache_reader.cpp
- src/include/cache_filesystem.hpp
This PR updates a few things:
- httpfs file handle doesn't correctly handle parallel access, which could lead to data race
- Adjust offset update behavior based on httpfs implementation.
> Adjust offset update to httpfs behavior

- src/read_cache_fs_extension.cpp
- test/sql/disk_cache_filesystem.test
- test/sql/inmem_cache_filesystem.test
- Fix an issue that extension could be reloaded in the same process (for example, reset duckdb instance), so we need to reset all global variables at load
- Add sql tests for both in-memory and on-disk cache reader
> Fix extension reload and add sql test

- src/include/base_cache_reader.hpp
- src/include/base_profile_collector.hpp
Follows the C++ best practice.
> Disable copy and move semantics for a few classes

- CMakeLists.txt
- src/utils/include/copiable_value_lru_cache.hpp
- src/utils/include/string_utils.hpp
- src/utils/string_utils.cpp
- unit/test_copiable_value_lru_cache.cpp
- unit/test_string_utils.cpp
```
struct ImmutableBuffer {
std::shared_ptr<char[]> buffer;
std::size_t buf_size;
}
```
is so far the best data structure I could ever think of to represent an immutable buffer.
But unfortunately duckdb extension is only C++14, so we lack two important piece:
- `make_shard_for_overwrite`
- `std::optional`
In the next PR, I will integrate it with in-memory cache reader.
> Introduce immutable buffer for in-memory cache and corresponding LRU cache

- CMakeLists.txt
- src/in_memory_cache_reader.cpp
- src/include/in_memory_cache_reader.hpp
- src/utils/immutable_buffer.cpp
- src/utils/include/immutable_buffer.hpp
- unit/test_string_utils.cpp
This PR integrate immutable buffer into in-memory cache reader;
compared with previous `std::shared_ptr<std::string>`, we save one pointer direction and memory allocation for every access, thus better cache locality.
> [2/N] Integrate immutable buffer with in-memory cache reader

- src/cache_filesystem.cpp
- src/include/cache_filesystem.hpp
Issue: https://github.com/dentiny/duck-read-cache-fs/issues/100
The problem is file open could be called from multiple threads, thus data race on cache reader and profiler update.
> Fix file open data race

- test/sql/disk_cache_filesystem.test
- test/sql/inmem_cache_filesystem.test
- test/sql/noop_cache_filesystem.test
Add more test on `read_parquet` function; I use weblink instead of pulling the data into repository (as we did for csv test data) due to its size.
> Add test for `read_parquet`

- CMakeLists.txt
- src/cache_entry_info.cpp
- src/cache_filesystem.cpp
- src/cache_filesystem_ref_registry.cpp
- src/cache_httpfs_extension.cpp
- src/cache_status_query_function.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_cache_reader.hpp
- src/include/cache_entry_info.hpp
- src/include/cache_filesystem.hpp
- src/include/cache_filesystem_ref_registry.hpp
- src/include/cache_status_query_function.hpp
- src/include/disk_cache_reader.hpp
- src/include/in_memory_cache_reader.hpp
- src/include/noop_cache_reader.hpp
- src/utils/include/copiable_value_lru_cache.hpp
- test/sql/inmem_cache_filesystem.test
This function provides an insight on in-memory cache status. Example see below:
```
D SELECT * FROM cache_httpfs_cache_status_query();
┌─────────────────┬───────────────────────────────────┬──────────────┬────────────┬────────────┐
│ cache_filepath  │          remote_filename          │ start_offset │ end_offset │ cache_type │
│     varchar     │              varchar              │    uint64    │   uint64   │  varchar   │
├─────────────────┼───────────────────────────────────┼──────────────┼────────────┼────────────┤
│ (no disk cache) │ https://blobs.duckdb.org/data/t…  │    126877696 │  126943232 │ in-mem     │
│ (no disk cache) │ https://blobs.duckdb.org/data/t…  │    126943232 │  127008768 │ in-mem     │
│ (no disk cache) │ https://blobs.duckdb.org/data/t…  │    127008768 │  127056503 …
```
> Provide SQL function to query in-memory cache status

- src/cache_httpfs_extension.cpp
- src/cache_reader_manager.cpp
- src/cache_status_query_function.cpp
- src/disk_cache_reader.cpp
- src/include/cache_reader_manager.hpp
- src/include/disk_cache_reader.hpp
- test/sql/disk_cache_filesystem.test
Followup PR for https://github.com/dentiny/duck-read-cache-fs/pull/107
Example query:
```sql
SELECT * FROM cache_httpfs_cache_status_query();
----
/tmp/duckdb_cache_httpfs_cache/9a30b02c260f8209e5648653bcedd2e125f0a796061b24a0b996c4bc867d38c7-taxi_2019_04.parquet-126000000-1000000	taxi_2019_04.parquet	126000000	127000000	on-disk
/tmp/duckdb_cache_httpfs_cache/9a30b02c260f8209e5648653bcedd2e125f0a796061b24a0b996c4bc867d38c7-taxi_2019_04.parquet-127000000-56503	taxi_2019_04.parquet	127000000	127056503	on-disk
/tmp/duckdb_cache_httpfs_cache/c1b7e15bc8fe00a09fd6ea693ca6bdf109f622f26f4c6b34ad568a300854b5e2-stock-exchanges.csv-0-16222	stock/exchanges.csv	0	16222	on-disk
```
> Query cache status for disk cache

- CMakeLists.txt
- src/cache_httpfs_extension.cpp
- src/disk_cache_reader.cpp
- src/utils/fake_filesystem.cpp
- src/utils/include/fake_filesystem.hpp
- test/sql/disk_cache_filesystem.test
- test/sql/extension.test
- test/sql/inmem_cache_filesystem.test
- test/sql/noop_cache_filesystem.test
- test/sql/wrap_cache_filesystem.test
- unit/test_filesystem_utils.cpp
This PR registers an extension function, which allows users to wrap all possible filesystem with cache httpfs filesystem.
Also update duckdb to commit `981c7a8573b254f8efd6b71f764c5c3bd924a53d`.
> Ability to wrap and cache all registered filesystems

- README.md
- src/cache_httpfs_extension.cpp
- src/disk_cache_reader.cpp
Certain functions (i.e. getting filesystem profiles) relies on registered filesystem instances, and we should register customized filesystems also.
> Register customized filesystem

- src/disk_cache_reader.cpp
- src/utils/filesystem_utils.cpp
- unit/test_disk_cache_filesystem.cpp
This PR fixes a data race situation:
- Read thread checks the file exists, then open the file and update its access timestamp;
- Meanwhile deletion thread (i.e. user requests to read the same block) removes the cache file;
- Then we get a "file doesn't exist" error on read thread.
For duckdb, assume users don't (1) clear cache files and (2) read at the same time, it's still possible to suffer data race described above, when a cache file's at the edge of eviction threshold, and disk space is insufficient.
R: read block and cache hit
C: read block and cache miss -> start cache file deletion due to insufficient disk space
> Fix cache file open and read data race

- CONTRIBUTING.md
Did some experiment on how `ccache` helps improve compilation speed.
Commands to rebuild:
- delete all already built targets: `make clean`
- clean up page cache: `sudo sync; sudo sh -c "echo 3 > /proc/sys/vm/drop_caches"`
- rebuild from scratch: `time CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) make`
Without `ccache`
```sh
real    3m25.561s
user    64m55.043s
sys     2m51.529s
```
With `ccache` and cache hit:
```sh
real    0m56.167s
user    2m41.581s
sys     0m30.165s
```
> Mention ccache on contribution doc

- src/cache_filesystem.cpp
- src/cache_filesystem_config.cpp
- src/cache_httpfs_extension.cpp
- src/include/cache_filesystem_config.hpp
- Add config setting for metadata cache, to make preparations for file handle cache and glob cache;
- Fix config setting for left bytes for on-disk cache.
> Fix left bytes configuration for disk cache

- src/cache_filesystem.cpp
- src/disk_cache_reader.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_profile_collector.hpp
- src/include/cache_filesystem.hpp
- src/include/histogram.hpp
- src/include/temp_profile_collector.hpp
- src/noop_cache_reader.cpp
- src/temp_profile_collector.cpp
Addresses https://github.com/dentiny/duck-read-cache-fs/issues/119
Test SQL:
```sh
D SET cache_httpfs_profile_type='temp';
D EXPLAIN ANALYZE SELECT i,j FROM read_parquet('s3://duckdb-cache-fs/test_folder/**/*.parquet', hive_partitioning = true, union_by_name=True);
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYZE SELECT i,j FROM read_parquet('s3://duckdb-cache-fs/test_folder/**/*.parquet', hive_partitioning = true, union_by_name=True);
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││         HTTPFS HTTP Stats         ││
││                                   ││
││            in: 3.5 KiB …
```
> Add profiler for open and glob

- src/utils/include/exclusive_lru_cache.hpp
- unit/test_exclusive_lru_cache.cpp
I'm working on file handle cache, one thing I found is
- Internal file handle is cached in file handle cache;
- On cache file handle destruction, internal file handle is reset and placed into handle cache;
- To make internal file handle re-usable, cache handle's close function does nothing.
=> We have no way to close internal file handle, which leads to resource leak (i.e. fd).
The way I proposed here is 
- When a new item is kicked out due to LRU eviction policy, we get the value back;
- So we could get the file handle and close out of critical section.
> Get evicted value from lru cache

- src/cache_filesystem.cpp
- src/cache_filesystem_config.cpp
- src/cache_httpfs_extension.cpp
- src/include/base_profile_collector.hpp
- src/include/cache_filesystem.hpp
- src/include/cache_filesystem_config.hpp
- src/include/temp_profile_collector.hpp
- src/temp_profile_collector.cpp
- src/utils/include/exclusive_lru_cache.hpp
This PR implements the initial version of file handle cache.
Cache entries are populated when cache file handle gets destructed, then internal file handle resets and place into cache.
Testing SQL commands:
```sql
D SET cache_httpfs_profile_type='temp';
D EXPLAIN ANALYZE SELECT i,j FROM read_parquet('s3://duckdb-cache-fs/test_folder/**/*.parquet', hive_partitioning = true, union_by_name=True);
D COPY (SELECT cache_httpfs_get_profile()) TO '/tmp/output-1.txt';
```
Repeat the SQL statements for a few times, I did observe cache file handles are reused later.
There're two TODO items:
- Add file handle cache related config settings and functions;
- Consider if we need to store multiple file handles by one key, which turns out to be useful for the above SQL.
> Initial implementation for file handle cache

- src/cache_filesystem.cpp
- src/include/cache_filesystem.hpp
Followup PR for https://github.com/dentiny/duck-read-cache-fs/pull/133 and fix a bug:
- When we clear a file handle cache, we should close all resource for the file handles inside;
- Otherwise we have resource leak.
> Fix file handle cache deletion

- src/cache_entry_info.cpp
- src/cache_filesystem_config.cpp
- src/cache_httpfs_extension.cpp
- src/cache_status_query_function.cpp
- src/disk_cache_reader.cpp
- src/in_memory_cache_reader.cpp
- src/include/base_cache_reader.hpp
- src/include/base_profile_collector.hpp
- src/include/cache_entry_info.hpp
- src/include/cache_status_query_function.hpp
- src/include/disk_cache_reader.hpp
- src/include/in_memory_cache_reader.hpp
- src/include/noop_cache_reader.hpp
- src/include/temp_profile_collector.hpp
- src/temp_profile_collector.cpp
- test/sql/cache_access_info.test
- test/sql/disk_cache_filesystem.test
This PR provide cache access information via SQL function (with no latency distribution, which is too verbose).
Example SQL and effect:
```sql
D SELECT * FROM cache_httpfs_cache_access_info_query();
┌─────────────┬─────────────────┬──────────────────┐
│ cache_type  │ cache_hit_count │ cache_miss_count │
│   varchar   │     uint64      │      uint64      │
├─────────────┼─────────────────┼──────────────────┤
│ metadata    │               8 │                1 │
│ data        │               2 │                1 │
│ file handle │               0 │                3 │
└─────────────┴─────────────────┴──────────────────┘
```
> Provide SQL function to access cache access info

- CMakeLists.txt
- src/base_profile_collector.cpp
As titled, use static assertion to avoid we missing new items in the future.
> Add static assert for cache entity array and operation name array

- CMakeLists.txt
- src/cache_filesystem.cpp
- src/utils/include/string_utils.hpp
- src/utils/string_utils.cpp
- test/sql/cache_access_info.test
- unit/test_string_utils.cpp
I found even the given `path` is not glob expression, there's still glob operation.
Reference: https://github.com/dentiny/duck-read-cache-fs/issues/144
For these paths, we don't need to perform cache and profile, otherwise it's poluting cache and stats.
> Avoid profiling and caching for non-glob path

- src/utils/include/mock_filesystem.hpp
- src/utils/mock_filesystem.cpp
- unit/test_cache_filesystem_with_mock.cpp
- unit/test_exclusive_multi_lru_cache.cpp
Add a mock-based unit test, to make sure all cached file handles are properly closed and destructed.
Resolves https://github.com/dentiny/duck-read-cache-fs/issues/132
> Add mock test for handle close

- unit/test_cache_filesystem_with_mock.cpp
The lifecycle of mock filesystem lies in cache filesystem, so cannot access mock one after we destruct cache one.
> Fix invalid memory access for mock test

- unit/test_disk_cache_filesystem.cpp
This PR addresses part of issue #118 by enhancing test coverage for disk cache filesystem. 
* Reading only the last part of a file
> Add Additional Test Cases for Last Chunk Handling in Disk Cache Filesystem

- src/cache_filesystem.cpp
- test/sql/cache_access_info.test
We only place file handle to cache only when enabled, otherwise segfault (could be triggered by newly added sql test).
Also add test to verify the effect when all caches are disabled.
> Fix segfault for file handle cache

- src/cache_httpfs_extension.cpp
- test/sql/clear_cache.test
Followup PR for https://github.com/dentiny/duck-read-cache-fs/pull/162, which allows user to cleanup non-data block cache.
> Extension able to clear non-data cache

- src/cache_filesystem.cpp
- src/cache_filesystem_ref_registry.cpp
- src/cache_httpfs_extension.cpp
- src/cache_reader_manager.cpp
- src/in_memory_cache_reader.cpp
- src/noop_cache_reader.cpp
- src/temp_profile_collector.cpp
- src/utils/fake_filesystem.cpp
Pretty minor change, avoid destruct non-trivially destructible global variables, and cleanup header file inclusion order.
> [minor] Avoid destruct non-trivially destructible global variables

- test/sql/glob_read.test
Add two cached read test cases (reading data from the DuckDB github repo through httpfs)
1. Reading multiple Parquet files to test both cached and uncached read operations
2. Reading multiple CSV files with the `union by name` option to test both cached and uncached read operations
> Add sql test for glob read 

- src/cache_filesystem.cpp
This debug macro causes an error in `test_cache_filesystem_with_mock`, so we removed it.
> Remove debug macro in cache_filesystem

- doc/example_usage.md
This makes it easier for users to understand the cache_httpfs_cache_access_info_query() usage.
> Add cache_httpfs_cache_access_info_query result to doc

- src/base_profile_collector.cpp
- src/include/base_profile_collector.hpp
Fails on community extension CI unfortunately, have to downgrade to C++11 grammar.
> Use C++11 static constexpr

- src/include/base_profile_collector.hpp
Get certain error message at community extension CI:
```sh
/duckdb_build_dir/src/include/base_profile_collector.hpp:105:79: error: no match for 'operator[]' (operand types are 'const std::array<const char*, 4>' and 'duckdb::idx_t' {aka 'long unsigned int'})
105 |                         cache_access_info[idx].cache_type = CACHE_ENTITY_NAMES[idx];
|                                                                               ^
```
Use `size_t` instead, hopefully it works (since we used it elsewhere at last release).
> Use size_t for std::array

- CONTRIBUTING.md
Before submitting PR to duckdb community extension repo, we need to make sure extension compiles and runs fine with the provided docker file.
> Add instruction to check at community extension CI environment

- CMakeLists.txt
- src/base_profile_collector.cpp
- src/include/base_profile_collector.hpp
Duckdb needs to support musl libc, which doesn't seem to support `operator[]` for `std::array<>` somwhow, so I use `std::vector` instead.
Related
- release instruction: https://github.com/dentiny/duck-read-cache-fs/blob/main/CONTRIBUTING.md#release-process
- issue: https://github.com/duckdb/extension-ci-tools/issues/163
> Fix compilation musl

- src/cache_httpfs_extension.cpp
- test/sql/wrap_cache_filesystem.test
As of today, latest duckdb release v1.2.1 doesn't support sub-filesystem extraction: https://github.com/duckdb/duckdb/pull/16226; so wrapping other filesystems doesn't compile at duckdb CI pipeline.
Because I'm not sure whether it will be supported in v1.2.2, so I temporarily disable the related function to unblock new version release; after it's supported in duckdb official release version, I will do a new patch release.
> Temporarily disable wrap filesystem

- src/cache_httpfs_extension.cpp
- test/sql/extension.test
Related issue https://github.com/duckdb/duckdb/discussions/17005
Before change
```sql
D SELECT * FROM duckdb_extensions() WHERE extension_name = 'cache_httpfs';
┌────────────────┬─────────┬───────────┬──────────────┬─────────────┬───────────┬───────────────────┬───────────────────┬────────────────┐
│ extension_name │ loaded  │ installed │ install_path │ description │  aliases  │ extension_version │   install_mode    │ installed_from │
│    varchar     │ boolean │  boolean  │   varchar    │   varchar   │ varchar[] │      varchar      │      varchar      │    varchar     │
├────────────────┼─────────┼───────────┼──────────────┼─────────────┼───────────┼───────────────────┼───────────────────┼────────────────┤
│ cache_httpfs   │ true    │ true      │ (BUILT-IN)   │             │ []        │ …
```
> Add extention load info

- src/cache_httpfs_extension.cpp
- src/cache_status_query_function.cpp
- src/include/cache_status_query_function.hpp
- test/sql/wrapped_filesystems_info.test
Implement https://github.com/dentiny/duck-read-cache-fs/issues/183
```sql
SELECT * FROM cache_httpfs_get_cache_filesystems();
----
cache_httpfs with HTTPFileSystem
cache_httpfs with HuggingFaceFileSystem
cache_httpfs with S3FileSystem
```
> Provide a table function to list all wrapped DuckDB filesystems

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Devcontainer is useful to ease development environment setup, and widely used in a number of well-known projects, like [pg_mooncake](https://github.com/nbiscaro/pg_mooncake/tree/ad0b28d1873bffb8c835e1a52d472d91c9a95de3/.devcontainer).
> Add devcontainer setup for repository

- CMakeLists.txt
- src/cache_filesystem.cpp
- src/include/cache_filesystem.hpp
- src/utils/include/mock_filesystem.hpp
- unit/test_cache_filesystem.cpp
- unit/test_cache_filesystem_with_mock.cpp
Related to https://github.com/dentiny/duck-read-cache-fs/issues/195
This PR does a few things:
- Upgrade duckdb to release v1.3.0
- Upgrade two other dependencies, httpfs and ci-extension-tools as well
- Adapt to new glob API to pass build, but disable glob cache temporarily; will followup with another PR
> Upgrade duckdb dependency to v1.3.0

- src/cache_httpfs_extension.cpp
- test/sql/external_file_cache.test
Current implementation doesn't work well with duckdb native "external file cache", which is enabled by default.
So application actually suffers double caching, which is bad.
In this PR, I solve the problem by:
- Disable external file cache by default, when cache httpfs extension is loaded, since it's already covering all caching features with external cache;
- Users and application are still able to re-enable external cache by normal "SET enable_external_file_cache = true;"
Test SQL:
```sql
-- Initially external file cache is disabled by default.
D SELECT current_setting('enable_external_file_cache');
┌───────────────────────────────────────────────┐
│ current_setting('enable_external_file_cache') │
│                    boolean                    │ …
```
> Fix double caching

- src/include/cache_filesystem_config.hpp
This PR bumps up IO request size from 64KiB to 512Kib (8x), which also serves as cache block size.
From my past experience, 2MiB request size is usually the sweetspot for object storage system, I didn't make it in this PR because:
- Could lead to larger latency and more wasted memory due to alignment;
- Increasing from 64KiB to 2MiB is a 32x boost, I would like to make it a multi-step rollout process to reduce unexpectation.
Related to issue https://github.com/dentiny/duck-read-cache-fs/issues/214
> Bump up IO request size

- CMakeLists.txt
- benchmark/read_s3_object.cpp
- src/cache_filesystem_config.cpp
- src/cache_httpfs_extension.cpp
- src/disk_cache_reader.cpp
- src/include/cache_filesystem_config.hpp
- src/utils/include/filesystem_utils.hpp
- test/sql/disk_cache_filesystem_with_multi_cache_dir.test
- unit/test_cache_filesystem_with_mock.cpp
- unit/test_disk_cache_filesystem.cpp
- unit/test_disk_cache_with_multi_directories.cpp
- unit/test_large_file_disk_reader.cpp
- unit/test_large_file_inmem_reader.cpp
This PR adds cache directory config, which allows multiple cache directories;
and opens the possibilities to allow per-directory configuration in the future.
TODO items:
- Optimize cache directory parsing, current implementation does string parsing on every config access;
- Optimize situation where even after cache directories change, old cache files can still be accessed if possible.
Closes https://github.com/dentiny/duck-read-cache-fs/issues/215
> Add cache directory config

- src/cache_filesystem.cpp
- src/utils/include/mock_filesystem.hpp
- unit/test_cache_filesystem_with_mock.cpp
This PR attempts to extract file size attribute from glob return values, so it could be reused later.
> Extract and cache file size from open file info

- CMakeLists.txt
- extension_config.cmake
- src/cache_filesystem.cpp
- src/include/cache_filesystem.hpp
- src/utils/include/mock_filesystem.hpp
- src/utils/include/time_utils.hpp
- src/utils/time_utils.cpp
- unit/test_cache_filesystem_with_mock.cpp
This PR adds more file attributes to file metadata cache, not only file size.
I think the most difficult part is duckdb filesystem API, which should have a `Stat` call to get all file attributes.
I opened a discussion thread upstream: https://github.com/duckdb/duckdb/discussions/18489
> Add modification timestamp to metadata cache

- src/cache_filesystem.cpp
This is a bug: when cleaning up file handle cache for a particular entry, we shouldn't clear the whole cache.
> Fix file handle cache cleanup

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- inspired by moonlink
- able see the endpoint after re-build folder in the container
issue: https://github.com/dentiny/duck-read-cache-fs/issues/63
> feat: support local endpoint for httpfs usage

- src/cache_filesystem_config.cpp
- src/cache_httpfs_extension.cpp
- src/disk_cache_reader.cpp
- src/include/cache_filesystem_config.hpp
- src/include/disk_cache_reader.hpp
- unit/test_disk_cache_filesystem.cpp
This PR adds a basic single-process based LRU cache block eviction: when there's insufficient disk space under cache directory, evict cache blocks based on their modification (aka, creation) timestamp.
Making multi-process LRU is complicated, for example, multiple processes could be writing cache blocks to the same directory. To keep LRU relatively precise, either we delay stat on insufficient disk space, or we maintain an internal background thread to keep it updated at real-time.
Related to https://github.com/dentiny/duck-read-cache-fs/issues/238
> Evict on-disk cache block based on LRU
