dentiny/duck-read-cache-fs

src/utils/filesystem_utils.cpp
src/utils/include/filesystem_utils.hpp
unit/test_disk_cache_filesystem.cpp

Add two local filesystem util functions, which could be used in all unit tests.

Add filesystem util function for test cases

---

CMakeLists.txt
src/base_cache_filesystem.cpp
src/include/base_cache_filesystem.hpp
src/include/cache_filesystem_config.hpp
src/include/noop_cache_reader.hpp
src/noop_cache_reader.cpp
unit/test_noop_cache_reader.cpp

See issue https://github.com/dentiny/duck-read-cache-fs/issues/40

Implement noop cache reader

---

Makefile

As titled. I manually checked by intentionally modifying cmakelist, and make sure it works as expected.

Add linter for cmakelist

---

src/cache_filesystem_config.cpp
src/include/cache_filesystem_config.hpp

Fix missing cache type, which disallow users to fallback to no-op cache reader.

Fix missing cache type

---

CMakeLists.txt
src/include/base_cache_reader.hpp
src/include/base_profile_collector.hpp
src/include/cache_filesystem.hpp
unit/test_filesystem_config.cpp

... so we could guard against two issues discovered before.

Add unit test for cache and profiler config setting

---

Makefile
src/read_cache_fs_extension.cpp
test/data/stock-exchanges.csv
test/sql/extension.test

We are following the duckdb extension template by setting up a test directory and a sql/ subdirectory within. We will store all sqllogictests in it.
To run all SQLLogicTests, use the following command:
```
make sqllogictest 
```

Sqllogictest setup

---

vcpkg.json

At the very beginning of the project, I wasn't following the extension repo's setting;
this PR tries to save by copying the necessary files over.

Merge community extension template

---

CONTRIBUTING.md
README.md
example/example_usage.md
src/cache_filesystem_config.cpp
test/sql/extension.test

This PR does a few things:
- Add example usage page, which lists a few common operations and config settings
- Update readme page, which covers commands to install and load from community 
- Include C++ unit test guide on contributing page
- Fix a potential bug for invalid config value and add corresponding test

Update README page and add example usage

---

README.md
doc/example_usage.md

I forgot to add documentation in the previous PR.

Doc for filesystem wrapper

---

CMakeLists.txt
benchmark/random_read_benchmark.cpp
benchmark/read_s3_object.cpp
benchmark/sequential_read_benchmark.cpp
src/cache_filesystem.cpp
src/cache_filesystem_config.cpp
src/cache_httpfs_extension.cpp
src/cache_reader_manager.cpp
src/disk_cache_reader.cpp
src/include/base_profile_collector.hpp
src/include/cache_filesystem_config.hpp
src/include/temp_profile_collector.hpp
src/temp_profile_collector.cpp
src/utils/fake_filesystem.cpp
src/utils/include/no_destructor.hpp
unit/test_disk_cache_filesystem.cpp
unit/test_filesystem_config.cpp
unit/test_in_memory_cache_filesystem.cpp
unit/test_no_destructor.cpp
unit/test_noop_cache_reader.cpp

Addresses https://github.com/dentiny/duck-read-cache-fs/issues/125

Introduce NoDestructor<> wrapper and avoid global variable to destruct

---

CMakeLists.txt
src/utils/include/exclusive_multi_lru_cache.hpp
unit/test_exclusive_multi_lru_cache.cpp

See problem statement https://github.com/dentiny/duck-read-cache-fs/issues/117#issuecomment-2742231238
We need to have a LRU cache which caches multiple values with the same key.

Implement exclusive multi LRU cache

---

CMakeLists.txt
src/base_profile_collector.cpp
src/cache_entry_info.cpp
src/cache_filesystem.cpp
src/cache_filesystem_config.cpp
src/cache_httpfs_extension.cpp
src/include/base_profile_collector.hpp
src/include/cache_filesystem.hpp
src/include/cache_filesystem_config.hpp
test/sql/cache_access_info.test
unit/test_cache_filesystem.cpp
unit/test_disk_cache_filesystem.cpp

Add an eventual consistency cache for GLOB operation.

Add glob cache

---

src/cache_filesystem_config.cpp

Fixes https://github.com/dentiny/duck-read-cache-fs/issues/150

Cap thread number for io requests

---

README.md
doc/example_usage.md

Add doc for file handle, metadata and glob operation cache.

Add documentation for other cache types

---

src/cache_filesystem.cpp
src/include/cache_filesystem.hpp

Update httpfs extension to include fix: https://github.com/duckdb/duckdb-httpfs/pull/17
And update corresponding file offset update logic.

Upgrade httpfs and file offset update

---

src/utils/include/exclusive_multi_lru_cache.hpp
unit/test_exclusive_multi_lru_cache.cpp

For the existing function to clear cache by filename: https://github.com/dentiny/duck-read-cache-fs/blob/faa0a5da39e8403d8eb58812dbbf1c223de27a11/src/cache_httpfs_extension.cpp#L260-L264
it applies to metadata cache and file handle cache as well.
This PR adds clear function in exclusive multi-lru cache, also fix a bug for cache implementation.

Clear cache entry for exclusive multi LRU cache

---

CONTRIBUTING.md

Suggested by https://github.com/duckdb/community-extensions/pull/346#issuecomment-2780398504 to update duckdb version to the latest stable version v1.2.1

Update duckdb v1.2.1

---

CMakeLists.txt

Upgrade two dependencies for this extension to keep up-to-date.

Upgrade httpfs and extension-ci-tools

---

doc/example_usage.md

This PR adds documentation on how to set multiple cache directories for the extension.

Add cache directory config documentation

---

src/disk_cache_reader.cpp

`std::hash<>` doesn't provide deterministic hash across platform, which causes CI to fail;
switch to self-implemented hash function for deterministic directory index value.

Use deterministic hash for dir idx

---

CHANGELOG.md
CMakeLists.txt

This PR upgrades duckdb to v1.4.1 and extension-ci / httpfs to latest version.

Upgrade all dependencies
